import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import HeaderSection from "@/components/headerSection";
import { ImageContext } from "@/components/contextApi/imageContext";
import { useState } from "react";
import ImageProvider from "@/components/contextApi/imageProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ImageProvider>
          <HeaderSection />
          {children}
          <Footer />
        </ImageProvider>
      </body>
    </html>
  );
}
